#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.datasource.url=jdbc:mysql://123.57.84.78:3306/ttx_app_push
#spring.datasource.username=root
#spring.datasource.password=Rongdong520@!
server:
  port: 8080

spring:
    http:
        multipart:
            max-file-size: 128KB
            max-request-size: 128KB

    mail:
        host: smtp.163.com
        username: hshandzmq@163.com
        password: han930607QWE
        port: 25
        protocol: smtp
        default-encoding: UTF-8

    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://123.57.84.78:3306/ttx_app_push
        username: root
        password: Rongdong520@!
        type: com.alibaba.druid.pool.DruidDataSource
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

    redis:
        database: 1
        timeout: 5000
        host: 123.57.84.78
        port: 6379
        password: Rongdong520
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 500
          min-idle: 2
          testOnBorrow: true


mybatis:
        mapper-locations: classpath:mapping/*.xml #指明mapper的xml文件存放位置
        type-aliases-package: com.udemo.model    #指明和数据库映射的实体的所在包

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

